### ISSUE TITLE
Restarting

### ISSUE THREAD

**Issue by middelink** [SensorsIot/Reminder-with-Google-Calender#1]
There seems to be a problem with the persistence of still active (but expired events in Gcal) events. On startup it starts fresh, re-reads what is available in the Calendar and sets the led accordingly. However as the event is now due in Calendar, it is not seen, even though it has /not/ been acknowledged. Oops. one power failure and the missus is mad at you again :P

It would be advisable to store the active, unacked state in eeprom as well, so that at startup we still know we had an un-acked event.

**Comment by SensorsIot** [comment]
Why would you reboot a productive ESP? If this happens, I would first search for the reason for the reboot. But I think, it should be possible to put it in "EEPROM". Unfortunately, I do not have the time to do it.

**Comment by middelink** [comment]
Really? Your setup, both hardware and software, is perfect and it never reboots? Awesome.
the power could fail for one, maybe it is battery powered and you did not bother checking the calendar entry to replace the battery. Or replacing the battery for that matter, or you do an upgrade of the firmware or... or... too many reason why you would want to restart the esp

**Comment by witchole** [comment]
Good idea!
I've just submitted an enhanced version of the sketch that does store the status to permanent memory.
