### ISSUE TITLE
Could not connect to server: script.google.com

### ISSUE THREAD

**Issue by BJORNDEBEN** [SensorsIot/Reminder-with-Google-Calender#3]
hey, 
Can anyone help me out? I have build Andreas his project with 4 buttons and 4 leds.

**Comment by BJORNDEBEN** [comment]
for some reason I cant connect. what can I try or check.
I would like to get it working. I am using the first version of andreas his script. I only need to read the calendar. I also tried V2 but this version has similar problems. for some reason it will not connect.



 this is what shows in the serial monitor:

Connecting to wifi: S&B 2.4
.
WiFi connected
IP address: 
192.168.1.241
Port:443
Connecting to script.google.com
Connection failed. Retrying...
Connection failed. Retrying...
Connection failed. Retrying...
Connection failed. Retrying...
Connection failed. Retrying...
Could not connect to server: script.google.com
Exiting...
Start Request
Error! Not connected to host.
Calender Data error
Task 0 Status 0
Task 1 Status 0
Task 2 Status 0
Task 3 Status 0
----------
Task 0 Status 0
Task 1 Status 0
Task 2 Status 0
Task 3 Status 0
----------
Task 0 Status 0
Task 1 Status 0
Task 2 Status 0
Task 3 Status 0
----------
Task 0 Status 0
Task 1 Status 0
Task 2 Status 0
Task 3 Status 0
----------
Task 0 Status 0
Task 1 Status 0
Task 2 Status 0
Task 3 Status 0
----------
Start Request
Error! Not connected to host.
Calender Data error

**Comment by SensorsIot** [comment]
Did you set this "anonymous" flag shown in the video? For me, it only worked with this flag.

**Comment by BJORNDEBEN** [comment]
Hey,

 thank you for the quick response. Yes I did set the anonymous. Watched your video over and over again but for some reason it won't work. I tested the script for the 8 button version and it has the same problem.

**Comment by mohir** [comment]
Hello,
Check the version on the ESP8266 board in the Arduino IDE,
choose version 2.4.2,
It worked for me
hope it helps :)

**Comment by BJORNDEBEN** [comment]
Oké, great! Thank you very much! 
It finally works. I was working with a more recent version 2.5.0. I installed version 2.4.2 and uploaded the sketch. No problems anymore. The sketch also uploaded much faster. 

Thank you Mohir and thank you Andreas!
