### ISSUE TITLE
Can't get CreateCalendarEvent.gs to run.

### ISSUE THREAD

**Issue by Darius-Night** [SensorsIot/Reminder-with-Google-Calender#7]
This is the error i'm getting when the code is run in doGet:
6:28:47 PM
Notice
Execution started
6:28:47 PM
Error
TypeError: Cannot read property 'parameter' of undefined
doGet
@ 

I have no idea what i'm doing wrong.

I used the code from the file:
function doGet(eve){
  var title = eve.parameter.title;
  Logger.log(eve);
 //Logger.log(ContentService.createTextOutput(CreateEvent()));
  return ContentService.createTextOutput(CreateEvent(title));
}

// Replace XXX with your calendar name
function CreateEvent(eve){
  var _calendarName = 'Aufgaben_Familie'
  var MILLIS_PER_HOUR = 1000 * 60 * 15 ;
  var now = new Date();
  var from = new Date(now.getTime()-60000);
  var to = new Date(now.getTime() + 1 * MILLIS_PER_HOUR);
  var vCalendar = CalendarApp.getCalendarsByName(_calendarName)[0];
   vCalendar.createEvent(eve,
                        from,
                        to)
// Logger.log(currentTime);
//  Logger.log(vStartDateValue);
// Logger.log(from);
// Logger.log(to);
//  Logger.log(vEndDateValue);
return true;
}

**Comment by witchole** [comment]
Hi Darius,
Did you deploy the script?

**Comment by Darius-Night** [comment]
Now i found my error, i've run both gs-scrips in one google application. Now they run and in have 2 keys.
